### PR TITLE
Fixed 'Patching failed with inconsistencies' warning due to inaccurate expected response from K8s API

### LINKED ISSUE #574: Observing "Patching failed with inconsistencies" warning, but status is patched successfully
## Question

I'm observing a warning about "Patching failed with inconsistencies" .. but it appears to me that the status has been successfully patched.

I've checked the RBAC permissions, but they seem okay.

I've added some debugging to https://github.com/nolar/kopf/blob/0.28/kopf/reactor/effects.py that looks like this:
```
     if patch:
+        logger.debug(f"Body: {body!r}")
         logger.debug(f"Patching with: {patch!r}")
         resulting_body = await patching.patch_obj(resource=resource, patch=patch, body=body)
+        logger.debug(f"Resulting body: {resulting_body!r}")
         inconsistencies = diffs.diff(patch, resulting_body, scope=diffs.DiffScope.LEFT)
```

Here's the output of that debugging:
```
[2020-11-03 23:29:05,525] kopf.objects         [DEBUG   ] [trsdev05/jayp-app-cloudformation-stacks-trsdev05] Body: {'apiVersion': 'reece.tech/v1alpha1', 'kind': 'CloudformationDeployment', 'metadata': {'annotations': {'kopf.zalando.org/last-handled-configuration': '{"spec": {"stacks": [{"assume_role": "arn:aws:iam::123456789000:role/basic/kloudformator-assume-role", "name": "jayp-app-stack-one-trsdev05", "preserve_tags": ["^reecetech:.*$", "phileatseggs"], "region": "ap-southeast-2", "tags": {"CostCentre": 3973, "Environment": "infra", "Name": "jayp-app-stack-one-trsdev05", "Owner": "Delivery Engineering", "SomeOtherTag": "See, other tags work too"}, "template": "---\\nAWSTemplateFormatVersion: \'2010-09-09\'\\nDescription: A template that does nothing\\n\\nConditions:\\n  HasNot: !Equals [ \'true\', \'false\' ]\\n\\n# dummy resource, never created because of the Condition\\nResources:\\n  NullResource:\\n    Type: \'Custom::NullResource\'\\n    Condition: HasNot\\n"}, {"assume_role": "arn:aws:iam::065001841352:role/basic/kloudformator-assume-role", "name": "jayp-app-stack-two-trsdev05", "preserve_tags": ["^reecetech:.*$", "foobarbazspam"], "region": "ap-southeast-2", "tags": {"CostCentre": 3973, "Environment": "infra", "Name": "jayp-app-stack-two-trsdev05", "Owner": "Delivery Engineering", "SomeOtherTag": "Because why stop at the Reece mandatory ones?"}, "template": "---\\nAWSTemplateFormatVersion: \'2010-09-09\'\\nDescription: A template that does nothing\\n\\nConditions:\\n  HasNot: !Equals [ \'true\', \'false\' ]\\n\\n# dummy resource, never created because of the Condition\\nResources:\\n  NullResource:\\n    Type: \'Custom::NullResource\'\\n    Condition: HasNot\\n"}]}}'}, 'creationTimestamp': '2020-11-02T06:30:59Z', 'finalizers': ['kopf.zalando.org/KopfFinalizerMarker'], 'generation': 5, 'managedFields': [{'apiVersion': 'reece.tech/v1alpha1', 'fieldsType': 'FieldsV1', 'fieldsV1': {'f:spec': {}}, 'manager': 'Go-http-client', 'operation': 'Update', 'time': '2020-11-02T06:30:59Z'}, {'apiVersion': 'reece.tech/v1alpha1', 'fieldsType': 'FieldsV1', 'fieldsV1': {'f:spec': {'f:stacks': {}}}, 'manager': 'dashboard', 'operation': 'Update', 'time': '2020-11-03T23:20:07Z'}, {'apiVersion': 'reece.tech/v1alpha1', 'fieldsType': 'FieldsV1', 'fieldsV1': {'f:metadata': {'f:annotations': {'.': {}, 'f:kopf.zalando.org/last-handled-configuration': {}}, 'f:finalizers': {'.': {}, 'v:"kopf.zalando.org/KopfFinalizerMarker"': {}}}, 'f:status': {'.': {}, 'f:complete': {}, 'f:deleting': {}, 'f:failed': {}, 'f:rolled_back': {}, 'f:stacks': {}}}, 'manager': 'kopf', 'operation': 'Update', 'time': '2020-11-03T23:20:08Z'}], 'name': 'jayp-app-cloudformation-stacks-trsdev05', 'namespace': 'trsdev05', 'resourceVersion': '624106164', 'selfLink': '/apis/reece.tech/v1alpha1/namespaces/trsdev05/cloudformationdeployments/jayp-app-cloudformation-stacks-trsdev05', 'uid': '8bf6eb51-9c00-4c75-8778-58620b67fc16'}, 'spec': {'stacks': [{'assume_role': 'arn:aws:iam::123456789000:role/basic/kloudformator-assume-role', 'name': 'jayp-app-stack-one-trsdev05', 'preserve_tags': ['^reecetech:.*$', 'phileatseggs'], 'region': 'ap-southeast-2', 'tags': {'CostCentre': 3973, 'Environment': 'infra', 'Name': 'jayp-app-stack-one-trsdev05', 'Owner': 'Delivery Engineering', 'SomeOtherTag': 'See, other tags work too'}, 'template': "---\nAWSTemplateFormatVersion: '2010-09-09'\nDescription: A template that does nothing\n\nConditions:\n  HasNot: !Equals [ 'true', 'false' ]\n\n# dummy resource, never created because of the Condition\nResources:\n  NullResource:\n    Type: 'Custom::NullResource'\n    Condition: HasNot\n"}, {'assume_role': 'arn:aws:iam::065001841352:role/basic/kloudformator-assume-role', 'name': 'jayp-app-stack-two-trsdev05', 'preserve_tags': ['^reecetech:.*$', 'foobarbazspam'], 'region': 'ap-southeast-2', 'tags': {'CostCentre': 3973, 'Environment': 'infra', 'Name': 'jayp-app-stack-two-trsdev05', 'Owner': 'Delivery Engineering', 'SomeOtherTag': 'Because why stop at the Reece mandatory ones?'}, 'template': "---\nAWSTemplateFormatVersion: '2010-09-09'\nDescription: A template that does nothing\n\nConditions:\n  HasNot: !Equals [ 'true', 'false' ]\n\n# dummy resource, never created because of the Condition\nResources:\n  NullResource:\n    Type: 'Custom::NullResource'\n    Condition: HasNot\n"}]}, 'status': {'complete': False, 'deleting': False, 'failed': False, 'rolled_back': False, 'stacks': [{'name': 'jayp-app-stack-one-trsdev05', 'status': 'UPDATE_COMPLETE'}, {'name': 'jayp-app-stack-two-trsdev05', 'status': 'UPDATE_COMPLETE'}]}}
[2020-11-03 23:29:05,525] kopf.objects         [DEBUG   ] [trsdev05/jayp-app-cloudformation-stacks-trsdev05] Patching with: {'status': {'stacks': [{'name': 'jayp-app-stack-one-trsdev05', 'status': 'UPDATE_COMPLETE'}, {'name': 'jayp-app-stack-two-trsdev05', 'status': 'UPDATE_COMPLETE'}], 'complete': True}}
[2020-11-03 23:29:05,586] kopf.objects         [DEBUG   ] [trsdev05/jayp-app-cloudformation-stacks-trsdev05] Resulting body: {'status': {'apiVersion': 'reece.tech/v1alpha1', 'kind': 'CloudformationDeployment', 'metadata': {'annotations': {'kopf.zalando.org/last-handled-configuration': '{"spec": {"stacks": [{"assume_role": "arn:aws:iam::123456789000:role/basic/kloudformator-assume-role", "name": "jayp-app-stack-one-trsdev05", "preserve_tags": ["^reecetech:.*$", "phileatseggs"], "region": "ap-southeast-2", "tags": {"CostCentre": 3973, "Environment": "infra", "Name": "jayp-app-stack-one-trsdev05", "Owner": "Delivery Engineering", "SomeOtherTag": "See, other tags work too"}, "template": "---\\nAWSTemplateFormatVersion: \'2010-09-09\'\\nDescription: A template that does nothing\\n\\nConditions:\\n  HasNot: !Equals [ \'true\', \'false\' ]\\n\\n# dummy resource, never created because of the Condition\\nResources:\\n  NullResource:\\n    Type: \'Custom::NullResource\'\\n    Condition: HasNot\\n"}, {"assume_role": "arn:aws:iam::065001841352:role/basic/kloudformator-assume-role", "name": "jayp-app-stack-two-trsdev05", "preserve_tags": ["^reecetech:.*$", "foobarbazspam"], "region": "ap-southeast-2", "tags": {"CostCentre": 3973, "Environment": "infra", "Name": "jayp-app-stack-two-trsdev05", "Owner": "Delivery Engineering", "SomeOtherTag": "Because why stop at the Reece mandatory ones?"}, "template": "---\\nAWSTemplateFormatVersion: \'2010-09-09\'\\nDescription: A template that does nothing\\n\\nConditions:\\n  HasNot: !Equals [ \'true\', \'false\' ]\\n\\n# dummy resource, never created because of the Condition\\nResources:\\n  NullResource:\\n    Type: \'Custom::NullResource\'\\n    Condition: HasNot\\n"}]}}'}, 'creationTimestamp': '2020-11-02T06:30:59Z', 'finalizers': ['kopf.zalando.org/KopfFinalizerMarker'], 'generation': 5, 'managedFields': [{'apiVersion': 'reece.tech/v1alpha1', 'fieldsType': 'FieldsV1', 'fieldsV1': {'f:spec': {}}, 'manager': 'Go-http-client', 'operation': 'Update', 'time': '2020-11-02T06:30:59Z'}, {'apiVersion': 'reece.tech/v1alpha1', 'fieldsType': 'FieldsV1', 'fieldsV1': {'f:spec': {'f:stacks': {}}}, 'manager': 'dashboard', 'operation': 'Update', 'time': '2020-11-03T23:20:07Z'}, {'apiVersion': 'reece.tech/v1alpha1', 'fieldsType': 'FieldsV1', 'fieldsV1': {'f:metadata': {'f:annotations': {'.': {}, 'f:kopf.zalando.org/last-handled-configuration': {}}, 'f:finalizers': {'.': {}, 'v:"kopf.zalando.org/KopfFinalizerMarker"': {}}}, 'f:status': {'.': {}, 'f:complete': {}, 'f:deleting': {}, 'f:failed': {}, 'f:rolled_back': {}, 'f:stacks': {}}}, 'manager': 'kopf', 'operation': 'Update', 'time': '2020-11-03T23:29:05Z'}], 'name': 'jayp-app-cloudformation-stacks-trsdev05', 'namespace': 'trsdev05', 'resourceVersion': '624112539', 'selfLink': '/apis/reece.tech/v1alpha1/namespaces/trsdev05/cloudformationdeployments/jayp-app-cloudformation-stacks-trsdev05/status', 'uid': '8bf6eb51-9c00-4c75-8778-58620b67fc16'}, 'spec': {'stacks': [{'assume_role': 'arn:aws:iam::123456789000:role/basic/kloudformator-assume-role', 'name': 'jayp-app-stack-one-trsdev05', 'preserve_tags': ['^reecetech:.*$', 'phileatseggs'], 'region': 'ap-southeast-2', 'tags': {'CostCentre': 3973, 'Environment': 'infra', 'Name': 'jayp-app-stack-one-trsdev05', 'Owner': 'Delivery Engineering', 'SomeOtherTag': 'See, other tags work too'}, 'template': "---\nAWSTemplateFormatVersion: '2010-09-09'\nDescription: A template that does nothing\n\nConditions:\n  HasNot: !Equals [ 'true', 'false' ]\n\n# dummy resource, never created because of the Condition\nResources:\n  NullResource:\n    Type: 'Custom::NullResource'\n    Condition: HasNot\n"}, {'assume_role': 'arn:aws:iam::065001841352:role/basic/kloudformator-assume-role', 'name': 'jayp-app-stack-two-trsdev05', 'preserve_tags': ['^reecetech:.*$', 'foobarbazspam'], 'region': 'ap-southeast-2', 'tags': {'CostCentre': 3973, 'Environment': 'infra', 'Name': 'jayp-app-stack-two-trsdev05', 'Owner': 'Delivery Engineering', 'SomeOtherTag': 'Because why stop at the Reece mandatory ones?'}, 'template': "---\nAWSTemplateFormatVersion: '2010-09-09'\nDescription: A template that does nothing\n\nConditions:\n  HasNot: !Equals [ 'true', 'false' ]\n\n# dummy resource, never created because of the Condition\nResources:\n  NullResource:\n    Type: 'Custom::NullResource'\n    Condition: HasNot\n"}]}, 'status': {'complete': True, 'deleting': False, 'failed': False, 'rolled_back': False, 'stacks': [{'name': 'jayp-app-stack-one-trsdev05', 'status': 'UPDATE_COMPLETE'}, {'name': 'jayp-app-stack-two-trsdev05', 'status': 'UPDATE_COMPLETE'}]}}}
[2020-11-03 23:29:05,586] kopf.objects         [WARNING ] [trsdev05/jayp-app-cloudformation-stacks-trsdev05] Patching failed with inconsistencies: (('remove', ('status', 'stacks'), [{'name': 'jayp-app-stack-one-trsdev05', 'status': 'UPDATE_COMPLETE'}, {'name': 'jayp-app-stack-two-trsdev05', 'status': 'UPDATE_COMPLETE'}], None), ('remove', ('status', 'complete'), True, None))
[2020-11-03 23:29:05,687] kopf.objects         [DEBUG   ] [trsdev05/jayp-app-cloudformation-stacks-trsdev05] Something has changed, but we are not interested (the essence is the same).
[2020-11-03 23:29:05,687] kopf.objects         [DEBUG   ] [trsdev05/jayp-app-cloudformation-stacks-trsdev05] Handling cycle is finished, waiting for new changes since now.
```

Here's the output of `kubectl` showing that the status seems to be okay:

```
$ kubectl get cfndeploys -o=json --namespace=trsdev05 jayp-app-cloudformation-stacks-trsdev05
{
    "apiVersion": "reece.tech/v1alpha1",
    "kind": "CloudformationDeployment",
<...snip...>
    "status": {
        "complete": true,
        "deleting": false,
        "failed": false,
        "rolled_back": false,
        "stacks": [
            {
                "name": "jayp-app-stack-one-trsdev05",
                "status": "UPDATE_COMPLETE"
            },
            {
                "name": "jayp-app-stack-two-trsdev05",
                "status": "UPDATE_COMPLETE"
            }
        ]
    }
}
```

I'm wondering if I'm doing something wrong?  Is this a false alarm?  Do I need to fix something?

## Checklist

- [x] I have read the [documentation](https://kopf.readthedocs.io/en/latest/) and searched there for the problem
- [x] I have searched in the [GitHub Issues](https://github.com/nolar/kopf/issues?utf8=%E2%9C%93&q=) for similar questions

## Keywords

`Patching` `failed` `inconsistencies`

### PR DESCRIPTION
**Pull request by iExalt**
## What do these changes do?
Fixes #574. 

## Description

Kopf expected that the K8s API would respond with the sub-resource's body instead of the entire body upon `PATCH .../status`. This PR corrects this behavior so Kopf reads from `patched_body["status"]["status"]` instead of `patched_body["status"]`. 

The unit tests that touch the status subresource have also been updated to reflect this change.

## Issues/PRs

 

#574 

## Type of changes
- Bug fix (non-breaking change which fixes an issue)

## Checklist

- [x] The code addresses only the mentioned problem, and this problem only
- [x] I think the code is well written
- [x] Unit tests for the changes exist
- [x] Documentation reflects the changes
- [x] If you provide code modification, please add yourself to `CONTRIBUTORS.txt`

### CODE REVIEW

**Review by nolar — APPROVED** [review]

**Comment by nolar** [comment]
Approved. Now, let me try to revive the CI for this old branch. I might do some weird stuff now...

**Comment by iExalt** [comment]
Let me quickly fix my entry in `CONTRIBUTORS.txt`

**Comment by nolar** [comment]
@iExalt No rush. It seems, it will take some time until I either revive Travis CI, which is now out of credits and no way to top-up, or test the thing manually myself.

**Comment by nolar** [comment]
@iExalt This release/0.28 is also switched to GitHub Actions (#592). Can you please either rebase your branch on top of `release/0.28` (and force-push) or merge it into your branch (and just-push)? This will launch all the CI tests in GitHub.

**Comment by iExalt** [comment]
Merged and pushed

**Comment by nolar** [comment]
**Side-note:** The unit-tests were actually successful. It is an issue with the unit-test results uploading and an external GitHub Actions step. To be fixed later — extracted to #593. 

For now, I assume that the codebase is fine, both unit-tested and functionally tested with no errors, and can be merged.

**Review by nolar — APPROVED** [review]

**Comment by nolar** [comment]
@iExalt Released as [`kopf==0.28.1`](https://github.com/nolar/kopf/releases/tag/0.28.1). Congratulations! And thank you for your contribution!

**Pull request merged**
